name: Upload Docker image

on:
  push:
    branches:
      - main

jobs:
  upload-dev-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build -t bzp2010/opengauss_exporter:dev .

      - name: Push docker image
        run: |
          docker push bzp2010/opengauss_exporter:dev