name: E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start openGauss Servers
        run: |
          docker run --name opengauss1 --privileged=true -d -e GS_PASSWORD=TestNode123! -p 5432:5432 enmotech/opengauss:2.1.0
          docker run --name opengauss2 --privileged=true -d -e GS_PASSWORD=TestNode123! -p 5433:5433 enmotech/opengauss:2.1.0

      - name: Wait for database initialize finished
        run: |
          sleep 120

      - name: Modify exporter config
        run: |
          sed -i 's/gaussdb:gaussdb/gaussdb:TestNode123!/' config.yaml.example
          sed -i 's/127.0.0.1/172.17.0.1/' config.yaml.example

      - name: Build openGauss Exporter docker image
        run: |
          docker build -t opengauss_exporter .

      - name: Start openGauss Exporter container
        run: |
          cp config.yaml.example config.yaml
          docker run -d -v $(pwd)/config.yaml:/etc/opengauss_exporter.yaml -p 9188:9188 opengauss_exporter -c /etc/opengauss_exporter.yaml

      - name: Wait for first scrape
        run: |
          sleep 15

      - name: Save metrics
        run: |
          curl http://127.0.0.1:9188/metrics > metrics.txt

      - name: Archive metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics.txt
          path: metrics.txt
          retention-days: 5

      # - name: Setup debugger
      #   uses: mxschmitt/action-tmate@v1